### ISSUE TITLE
Question: best way to handle subcommands

### ISSUE THREAD

**Issue by glerchundi** [peterbourgon/ff#10]
Hi @peterbourgon, first of all thanks for contributing to the open source community with such an interesting abstraction package. I wasn't feeling comfortable with the current state-of-art regarding to cli handling and this is exactly was I was expecting.

I would like to ask if you're aware of a best practices guide, recommended lib or anything that helps about subcommands handling obviously combined with this package.

I created a PR in [`google/subcommands`](https://github.com/google/subcommands/pull/19) so that it would be fairly easy to integrate with this lib, but there are some parts of it that I dislike, for example, returning custom exit codes instead of plain old `error`s among other things.

Feel free to close this issue in case you consider it's a completely off-topic issue.

Thanks in advance,

**Comment by peterbourgon** [comment]
```go
func main() {
    fs := flag.NewFlagSet(...)
    var (
        global = fs.String("global", "test", "example global flag")
        // ...
    )
    fs.Parse(os.Args[1:])

    var err error
    switch fs.Arg(0) {
    case "subcommand1":
        err = runSubcommand1(fs.Args()[1:], global, ...)
    case "subcommand2":
        err = runSubcommand2(fs.Args()[1:], global, ...)
    default:
        usage()
    }
    // handle err
}

func runSubcommand1(args []string, global string, ...) error {
    fs := flag.NewFlagSet(...)
    var (
        specific = fs.String("specific", "xyz", "flag specific to the subcommand1 subcommand")
        // ...
    )
    fs.Parse(args)
    // ....
}
```

**Comment by glerchundi** [comment]
Thanks!

**Comment by glerchundi** [comment]
In case someone wants this, I decided to create a lightweight lib to handle subcommands mainly to combine with this library: [`glerchundi/subcommands`](https://github.com/glerchundi/subcommands).
