### ISSUE TITLE
ffcli.DefaultUsageFunc: Match output of FlagSet.PrintDefaults

### ISSUE THREAD

**Issue by abhinav** [peterbourgon/ff#105]
This issue is to discuss a possible change in behavior in advance of a PR.
Currently, `-h` on a `ffcli.Command` prints a FLAGS section like the following:

```
  -b=false  bool
  -d 0s     time.Duration
  -f 0      float64
  -i 0      int
  -s ...    string
  -x ...    collection of strings (repeatable)
```

Things to note:
- Flags use the placeholder "..." instead of "string", "int", or something more helpful.
- Flags are always on the same line as the flag usage. Usage text has to shift right if a flag with a different length is added.
- Defaults are printed in the help message instead of being put at the end of the usage text, which adds another case when usage text has to shift right.
- Usage text shifting right adds uncertainty to how much horizontal space is available to a help message for a flag.
- Doesn't handle newlines in the flag usage text; it'll wrap to the next line instead of being indented to match.

FlagSet.PrintDefaults, on the other hand, prints:

```
  -b        bool
  -d duration
            time.Duration
  -f float
            float64
  -i int
            int
  -s string
            string
  -x value
            collection of strings (repeatable)
```

Only short boolean flags are on the same line -- if they fit in that space. All other usage text is on the next line and indented.

Not visible in this example:
- non-zero defaults are added at the end in the form `(default: foo)`
- newlines in usage text are adjusted to match indentation of the rest of the text
- if the help text wraps a word with backticks, for example:

    ```
    path to input `file`
    ```

  then that word is treated as the placeholder in the help:

    ```
    -f file
              path to input file
    ```

It's not terribly difficult to change DefaultUsageFunc to match this behavior, but it is a change in behavior.
Are you open to such a change or would you prefer that users write a custom UsageFunc for this?

**Comment by peterbourgon** [comment]
I'm happy to make changes like the one that was merged, but I definitely don't want ff.DefaultUsageFunc to match flag.FlagSet.PrintDefaults — I consider the latter to be pretty user-unfriendly, overall.

**Comment by peterbourgon** [comment]
> Split flag and help across two lines if flag is long — you've indicated this is undesirable

👍 

> Support multi-line flag help message — I suspect this would be acceptable

I'd say this is out of scope for DefaultUsageFunc, and something you should solve with your own implementation. (IMO multi-line flag help messages are a code smell, so to speak, and should be fixed, though I understand reasonable people may disagree.)

> Move default value to the end of the help text; this will have the effect of only printing flag type (-f string) or back-ticked value name (-f file) instead of default value in help (-f out.txt)

I don't have strong opinions here.

**Comment by abhinav** [comment]
>> Move default value to the end of the help text; this will have the effect of only printing flag type (-f string) or back-ticked >> value name (-f file) instead of default value in help (-f out.txt)
>
> I don't have strong opinions here.

Likewise.

Honestly, the only one I considered actionable is multi-line help, but I'm okay with calling that not ffcli's problem.
Command.Usage provides the ability to plug in arbitrary behavior so DefaultUsageFunc doesn't have to do it all.
I will close the issue since I don't see anything else actionable.

Thanks for the discussion!
