### ISSUE TITLE
Nested Config

### ISSUE THREAD

**Issue by lmittmann** [peterbourgon/ff#107]
Would you be open to a PR that enables nesting inside JSON configurations? This would allow flags containing dots to be looked up at the corresponding path. E.g. the flag `a.b` could be configured inside `{"a": {"b":"xxx"}}`.

**Comment by peterbourgon** [comment]
Probably not.

**Comment by lmittmann** [comment]
This is possible with `fftoml`, why not allow it for json and yml?

**Comment by peterbourgon** [comment]
I think it may have been a mistake to allow it in `fftoml`.

But, upon reflection, I suspect my initial reaction may be too conservative, and there may be actual value in this feature.

I'm open to reviewing a change that allows nesting of configuration in this way, provided the API and behavior is consistent across ffyaml, fftoml, and ffjson.

**Comment by jolheiser** [comment]
This can be closed per #112 

Thanks again to both of you!
