### ISSUE TITLE
Expose flagSectionsConfig

### ISSUE THREAD

**Issue by flowchartsman** [peterbourgon/ff#116]
Probably your standard alpha oversight, but there doesn't seem to be any way to access flagSectionsConfig. In my particular case I want it so that my little microframework can selectively display user flags with a `FLAGS` section named after the service if any were provided, while always displaying the flags that the library provides in their own, named section. And `flagSectionsConfig.AlwaysSubtitle` looks to be just the ticket!

Excited to keep kicking the tires on the new version!

**Comment by peterbourgon** [comment]
The intent of package ffhelp was to provide "reasonable default[s] for most users" that serve "as example[s]" for users "who want different help output". I guess that's you! 😉 as your use case sounds pretty specific. IMO, specific enough that you should own it yourself -- copy the relevant code from package ffhelp into your project, and change it as you see fit.

More selfishly, I'm not sure I want to commit to an API for package ffhelp that includes the domain concepts asserted by the flagSectionsConfig or its associated constructor. I'm not even really convinced of the Section type! The important parts of the ffhelp API are the ffhelp.Flags and ffhelp.Command constructors, everything else I'm not sure if it makes sense to include.

**Comment by peterbourgon** [comment]
With that said, I'm happy to hear any argument otherwise :) My position is considered and intentional, but not strongly held.

**Comment by flowchartsman** [comment]
By and large, I agree, however I might also argue that always removing the title from the first section, no matter which one it is is counterintuitive, since it's kind of difficult to determine which section you're looking at once they've been generated.

I'm not averse to owning it myself, however it seems as if that would be more difficult than it needs to be, with some level of hackery.

Consider the following:

```go
var (
	rootFlags      *ff.CoreFlags //initialized elsewhere with something like ("lib flags")
	userFlags      *ff.Coreflags
)

//and later...
	flagN := rootFlags
	for i := range providedValues {
		providedValues[i].flags.SetParent(flagN)
		flagN = providedValues[i].flags
	}
	userFlags.SetParent(flagN)
	err := ff.Parse(userFlags, os.Args[1:],
		ff.WithEnvVars(),
		ff.WithConfigFileFlag("config"),
		ff.WithConfigFileParser(ff.PlainParser),
	)
	switch {
	case errors.Is(err, ff.ErrHelp):
		exitUsage(userFlags)
	case err != nil:
                 //...
	}
//...
func exitUsage(flags *ff.Coreflags) {
	serviceName := buildinfo.ServiceName
	if serviceName == "" {
		serviceName = "service flags"
	}
	var docs ffhelp.Help
	docs = append(docs, ffhelp.NewFlagsSections(flags)...)
	// didn't work
	// for d := range docs {
	// 	if strings.Contains(docs[d].Title, "userflags") {
	// 		docs[d].Title = fmt.Sprintf("FLAGS (%s)", serviceName)
	// 	}
	// }
	docs.WriteTo(os.Stderr)
	os.Exit(0)
}
```

If there are no user flags (only flags provided by the library), the output is something like this:

```
$ mybin --help
FLAGS
  --metrics BOOL                        enable metrics (default: true)
  --profiling BOOL                      enable profiling (default: true)
  --log-level <debug|info|warn|error>   logging level (default: info)
  --log-format <text|json|human|auto>   logging format - "auto" will pick 'human' if attached to tty, 'json' otherwise (default: auto)
  --config STRING                       config file
```

This has no sections titles.

If the user provides any flag at all, we get:

```
$ mybin --help
FLAGS
  --myflag BOOL                         a flag the user wants (default: true)

FLAGS (lib flags)
  --metrics BOOL                        enable metrics (default: true)
  --profiling BOOL                      enable profiling (default: true)
  --log-level <debug|info|warn|error>   logging level (default: info)
  --log-format <text|json|human|auto>   logging format - "auto" will pick 'human' if attached to tty, 'json' otherwise (default: auto)
  --config STRING                       config file
```

Which has an unnamed section and a named one

Meanwhile, if I try this:

```go
func newExitUsage(flagSections ...*ff.CoreFlags) {
	var docs ffhelp.Help
	for _, f := range flagSections {
		// if f.NumFlags() == 0 {  // actually cannot check this
		// 	continue
		// }
		docs = append(docs, ffhelp.NewFlagsSection(f))
	}
	docs.WriteTo(os.Stderr)
}
```

I cannot easily skip an empty section (which would lead to a panic) that I'm aware of without using WalkFlags.

However, even in the case that every `*ff.CoreFlags` is populated, now I get _no_ sections, and no nice shared columnar layout either.

```
FLAGS
  --metrics BOOL                        enable metrics (default: true)
  --profiling BOOL                      enable profiling (default: true)
  --metrics-print-interval DURATION     dumps metrics to stdout at the provided interval (default: 10s)
  --log-level <debug|info|warn|error>   logging level (default: info)
  --log-format <text|json|human|auto>   logging format - "auto" will pick 'human' if attached to tty, 'json' otherwise (default: auto)
  --config STRING                       config file

FLAGS
  --myflag BOOL   a flag the user wants (default: true)
exit status 1
```

It's entirely possible I've missed something. I do recall running across something that allowed column layout to be shared, so maybe this isn't as big a deal as all that, but I believe I'd still need to generate their help first and merge it together instead of parsing the shared flags first and then checking for `ErrHelp`, which seems more intuitive and efficient.

Again, I might just need to read more of the docs, but unless I missed something glaringly obvious, this is starting to look like a lot of work when there is a feature that does exactly what I want, and appeared to have been intended for export anyway?

- [struct fields are exported](https://github.com/peterbourgon/ff/blob/743f646567c561890ce36edd5cf72b4cf0a3f102/ffhelp/section.go#L134-L137), 
- possible [doc comment block above](https://github.com/peterbourgon/ff/blob/743f646567c561890ce36edd5cf72b4cf0a3f102/ffhelp/section.go#L129-L131)?
- only referenced as a [config check](https://github.com/peterbourgon/ff/blob/743f646567c561890ce36edd5cf72b4cf0a3f102/ffhelp/section.go#L209-L211) as if it could be user-provided as an override.

Thoughts?

**Comment by flowchartsman** [comment]
If there is a way that I'm intended to do this, I'm obviously all ears, though this seems like a place where functional options might be the trick, even though I'm usually loathe to use them myself.

**Comment by flowchartsman** [comment]
I will note that using `ffhelp.Flags` is an improvement, since but it still eats the title for the first flags section, and I really wish it wouldn't. What would you recommend in terms of being more selective?

**Comment by peterbourgon** [comment]
Ah, interesting. My assumption was that anyone using a flag set directly wouldn't ever have any kind of parent hierarchy, and that parents would only be used via ff.Command. Consequently, I didn't intend for the help text from ffhelp.Flags to ever produce more than one FLAGS section. But it seems like `mybin` is a use case I haven't fully considered. Can you give me a bit more detail on how this program is structured? Is there a reason you're using flag sets directly, rather than commands?

> Thoughts?

I'm happy to hear your feedback, and am happy to consider changes to the new version, but -- just so I understand -- is there anything blocking you from implementing your own function which produces help text from a ff.Flags, or ff.CoreFlags?

> there is a feature that does exactly what I want, and appeared to have been intended for export

All the points you make are true, but please don't confuse my code cleanliness for any kind of intent to export 😉

**Comment by flowchartsman** [comment]
> Can you give me a bit more detail on how this program is structured? Is there a reason you're using flag sets directly, rather than commands?

Absolutely! But, just you you know, I was just now sitting down to write that, upon careful consideration I've decided to go with `text/tabwriter` and `Flags.WalkFlags` because I found myself agreeing with you.

So, rather than being a CLI application, this is intended as a bit of a micro-framework for generating the sort of services I continually find myself writing (i.e. boilerplate metrics, standardized structured logging with component loggers and wrappers for common clients, exported on-demand (and continuous) profiling routes, etcetera. Not intended for wide distribution, necessarily, but definitely to be used as a standard by a team of people.

The idea is that the library takes care of setting up all of the necessaries and has acertain base selection of flags to tweak this behavior (i.e. turning metrics on or off). This set is parsed very early, since it controls things such as log format, however it is retained for usage display and because it contains the config file directive that any one of the other flagsets could use. In case of `ErrHelp` or `ErrUnknownFlag` it is reset so that either of these can bubble up later alongside a usage display.

In addition, I've got an abstraction I'm working on called `FlagsProvider` (better name TBD), which is a generic interface that provides a flagset which it will then parse to generate a single concrete type. The idea here being you import (a very limited selection) of packages that define a `FlagsProvider` for standard downstream clients you need, such as databases and message queues that have particular configurations for your organization.

The third class of flags is a single flagset that is built up using global package methods (or perhaps an exported builder type) that allows for flags created by the user in `main()` for that specific service. Essentially, these methods mirror those of *ff.Coreflags`, but don't require the user to import `ff`.

So constructed, these three flag classes form the configuration for an application or service, and they share a common config file and a unified help view. I haven't looked into ff.Command too deeply, but seems to be more geared towards hierarchical CLIs with subcommands, while this is about compositionally building the configration for a single service with a dedicated configuration.

> I'm happy to hear your feedback, and am happy to consider changes to the new version, but -- just so I understand -- is there anything blocking you from implementing your own function which produces help text from a ff.Flags, or ff.CoreFlags?

No.  And this is pretty much exactly what I'm going to do :) 

> All the points you make are true, but please don't confuse my code cleanliness for any kind of intent to export 😉

Understood. We've all been there. I mean, my code is always perfect and bug-free, but I've heard other people deal with that sort of thing.

So, yeah, while I _do_ still feel like a couple more formatting directives wouldn't go amiss, this is not a hill I'd be willing to die on, so feel free to close this one out.

**Comment by peterbourgon** [comment]
> I've got an abstraction I'm working on called FlagsProvider (better name TBD), which is a generic interface that provides a flagset which it will then parse to generate a single concrete type. The idea here being you import (a very limited selection) of packages that define a FlagsProvider for standard downstream clients you need, such as databases and message queues that have particular configurations for your organization.

I see. I would definitely push back on this design.


Databases and message queues should define their configuration in terms of language-native types, which callers provide to them however they choose: from flags, via hard-coded values, chosen randomly from the ether, etc. 




Packages are stateless, so a package would never assert any specific set

**Comment by flowchartsman** [comment]
> Databases and message queues should define their configuration in terms of language-native types, which callers provide to them however they choose: from flags, via hard-coded values, chosen randomly from the ether, etc.

Broadly, yes. But within the context of an organization or a deployment, I think it makes complete sense to have a standard set of flags or environment variables which are shared across a set of related services (i.e. a configmap). In those instances, I think there's absolutely nothing wrong with removing the possibility of wasting several hours debugging a mistyping of a single flag in a single service by providing a standard (internal) import. That's the only point to this feature. Just like the flags, it is intended to enable individuals or teams to make their own lives more predictable.

> Packages are stateless, so a package would never assert any specific set
Having seen your edit to the above reply, I think we are on the same page now, so I don't need to quibble over this one.

> It's fine if you want to define a framework for flags at your organization, and define mappings between type-specific configurations and flags! But that's all "above" the core stuff itself.

I do still think there is a middle-ground that is in providing features which _enable_  a sort of meta-organizational framework targeted at teams/organizations, so long as the author doesn't get too big for their britches and attempt to start a new paradigm that everyone needs to adopt. There's some gray area there in the "opinionated framework" department, which is squarely where this falls, though I'm not the biggest fan of the term.

**Comment by peterbourgon** [comment]
> Broadly, yes. But within the context of an organization or a deployment, I think it makes complete sense to have a standard set of flags or environment variables which are shared across a set of related services (i.e. a configmap). In those instances, I think there's absolutely nothing wrong with removing the possibility of wasting several hours debugging a mistyping of a single flag in a single service by providing a standard (internal) import. That's the only point to this feature. Just like the flags, it is intended to enable individuals or teams to make their own lives more predictable.

Totally agree! But this is _exactly_ the kind of thing that I don't want to support in ff directly 😉 and _exactly_ the kind of thing which I hope can be built on top of ff -- if I've designed it good enough, at least.

**Comment by flowchartsman** [comment]
> they exist within package main and nowhere beyond that.

I assure you, we are on the same page. While the goal is to have convenience packages which provide a standardized _list_ of flags, their dispatch and the consumption of their resolution is entirely intended for package `main`. Years of doing this for a living have shown me the pain that results when you go beyond that, and I have been restructuring this such that it is difficult to abuse.
