### ISSUE TITLE
Current version

### ISSUE THREAD

**Issue by bodemann** [peterbourgon/ff#126]
go list -m -versions github.com/peterbourgon/ff
github.com/peterbourgon/ff v0.1.0 v1.0.0 v1.0.1 v1.0.2 v1.0.3 v1.1.0 v1.2.0 v1.3.0 v1.4.0 v1.5.0 v1.6.0 v1.7.0 v1.7.1

The latest version seems to be 3.4 and I cannot explain the difference. Is that intended, or am I doing something wrong? I hope I am not wasting your time with a beginner question.

Regards, Jörn

**Comment by peterbourgon** [comment]
Yeah, classic problem with SIV — you need to append /v2, /v3, etc.to the import path to get the actual latest version. Sorry.
