### ISSUE TITLE
Env var split with escape character ?

### ISSUE THREAD

**Issue by sentriz** [peterbourgon/ff#127]
hi! thanks for ff, i've been using it for [gonic](https://github.com/sentriz/gonic) for years 

there was a user today with an env var such as `GONIC_MPV_ARGS="--audio-device=alsa/iec958:CARD=ta,DEV=0"`

which resulting in an unwanted split. i know it can turned off or change the delimiter, but gonic does use the comma splitting for other flags already

i wonder is it feasible to comma escape the demilimiter like `a\,b`? 

thanks!

**Comment by peterbourgon** [comment]
Just to be clear, you're using `ff.WithEnvVarSplit(",")`?

**Comment by sentriz** [comment]
I'm still on v1 actually but yes that's the idea. I was hoping it would be possible to escape the env var split delim

**Comment by peterbourgon** [comment]
I think I understand, but just so there's no ambiguity, can you provide a complete example?

**Comment by sentriz** [comment]
sure, for example a docker-compose env, someone may have

```yaml
environment:
  - GONIC_MUSIC_PATHS="/a,/b"
  - GONIC_MPV_DEVICE="alsa/iec958:CARD=ta,DEV=0"
```

the first is correctly parsed as `[]string{"/a", "/b"}`, but the second is parsed as `[]string{"alsa/iec958:CARD=ta", "DEV=0"}` which in this case is not desired

i'm wondering if it makes sense to provide (or automatically) accept an escape character for the delimiter such as `\`, so that `alsa/iec958:CARD=ta\,DEV=0` could be parsed as `[]string{"alsa/iec958:CARD=ta,DEV=0"}` without an split

**Comment by peterbourgon** [comment]
Escaping isn't the path forward here — instead, call `ff.WithEnvVarSplit` with a different delimiter character, which is never valid in an env var value. For example `·` or `•` or etc.

**Comment by sentriz** [comment]
the trouble is that is global to the whole flag set, i need the delimiter to be `,` for some flags such GONIC_MUSIC_PATHS above

**Comment by sentriz** [comment]
thank you!
