### ISSUE TITLE
kv stores like consul?

### ISSUE THREAD

**Issue by flowchartsman** [peterbourgon/ff#14]
At least superficially it seems like adding support for something like consul (with or without prefix) might be nice, and I'd certainly be willing to make a companion lib as with the recommendation for #9, but this is an opinionated package, which means that ideals are important and I feel like you might have named it something other than `ConfigFileParser`, if you were prepared to allow external sources beyond config files. So I'm not sure whether a consul source (or really any source beyond configuration files) would be antithetical. Feel free to close, if so.

**Comment by peterbourgon** [comment]
Taking configuration from a process like Consul is definitely out-of-scope for this package.
