### ISSUE TITLE
weird behavior when finding keys in config file not defined in the flag set

### ISSUE THREAD

**Issue by vrischmann** [peterbourgon/ff#15]
Hi,

I'm writing a cli tool with mutiple subcommands and each subcommand has different flagset. 
I'm also using a config file since some flags are always required and they're annoying to type.

I thought I could use the same config file for each subcommand but it looks like `Parse` is too strict. I get an error like this:

    config file flag "debug" not defined in flag set

when my flag set doesn't define `debug`.

Note that with `v1.0.3` I get no error _but_ the parsing fails silently. 
I have a simple reproduction [here](https://gist.github.com/vrischmann/7170a20fe8aaf8dba3b2cefe95209433).

With `v1.0.3` here's the output:

    $ ./ff-repro foo
    2018/12/30 22:20:20 name:
    2018/12/30 22:20:20 age: 0
    $ ./ff-repro bar
    2018/12/30 22:20:24 age: 20
    2018/12/30 22:20:24 debug: true

which is clearly broken. With `master` I get this:

    $ ./ff-repro foo
    2018/12/30 22:24:04 config file flag "debug" not defined in flag set
    $ ./ff-repro bar
    2018/12/30 22:24:06 age: 20
    2018/12/30 22:24:06 debug: true

which is still not ideal (for me).

For my use case simply by returning nil [here](https://github.com/peterbourgon/ff/blob/master/parse.go#L45-L47) I get what I want (the value in the config file is ignored).

I'm wondering if this is something intentional ?

**Comment by peterbourgon** [comment]
You can write your own config file parser to have whatever behavior you want. I want/expect the included PlainParser to have the same behavior as encountering individual flag arguments as if they were flags. If you specify a flag that is not defined, the flag parsing errors out, so this is working as designed.

Options for you:

- Define your own config file parser
- Amend the existing config file parsers to include an error behavior, analogous to [flag.ErrorHandling](https://golang.org/pkg/flag/#ErrorHandling)
- Something else?

**Comment by vrischmann** [comment]
I'm ok with writing my config file parser however I don't see how I can I achieve what I want. I would need a way to not call the `set` function if the key I'm currently reading isn't present in the flagset but I don't have access to the flagset inside the `ConfigFileParser`.

Am I missing something ?

**Comment by peterbourgon** [comment]
Well, you'll always call Set, but Set may or may not return an error. I think.

**Comment by vrischmann** [comment]
Here's two subcommands:

    USAGE
      cleaver index-file [flags] file [file, ...]
    
    FLAGS
      -config path
            load config file from path (optional) (default "/home/vincent/.config/cleaver/config.txt")
      -data-dir directory
            store data inside directory

with the code:

	fs := flag.NewFlagSet("index-file", flag.ExitOnError)
	var (
		_                  = fs.String("config", defaultConfigFile(), "load config file from `path` (optional)")
		flDataDir          = fs.String("data-dir", "", "store data inside `directory`")
	)
	fs.Usage = usageFor(fs, "cleaver index-file [flags] file [file, ...]")

	ff.Parse(fs, args,
		ff.WithConfigFileFlag("config"),
		ff.WithConfigFileParser(ff.PlainParser),
	)

and another

    USAGE
      cleaver serve [flags]
    
    FLAGS
      -config path
            load config file from path (optional) (default "/home/vincent/.config/cleaver/config.txt")
      -data-dir directory
            store data inside directory
      -flush-interval duration
            Flush interval (default 10s)

with the code:

	fs := flag.NewFlagSet("serve", flag.ExitOnError)
	var (
		_                  = fs.String("config", defaultConfigFile(), "load config file from `path` (optional)")
		flDataDir          = fs.String("data-dir", "", "store data inside `directory`")

		flFlushInterval = fs.Duration("flush-interval", 10*time.Second, "Flush interval")
	)
	fs.Usage = usageFor(fs, "cleaver serve [flags]")

	ff.Parse(fs, args,
		ff.WithConfigFileFlag("config"),
		ff.WithConfigFileParser(ff.PlainParser),
	)

it's a truncated example from my program.

With a config file like this:

    data-dir /home/vincent/tmp
    flush-interval 20s

`ff.Parse` will fail when calling the `index-file` subcommand because `flush-interval` doesn't exist in its flag set. 
It makes sense but I was hoping to be able to reuse a single config file for all my subcommands.

But I just realized I can simply ignore the error returned by `set` inside a custom `ConfigFileParser`. Not ideal but it'll work.
