### ISSUE TITLE
PlainParser: # in config file value is interpreted as comment and truncates 

### ISSUE THREAD

**Issue by joeshaw** [peterbourgon/ff#16]
If you have a config file value that includes `#`, the value is truncated because PlainParser interprets the rest of the line as a comment, which is undesirable.

For example:
```
password abc#123
```

`password` is interpreted as `abc`, not `abc#123`.

I think there's probably no legitimate cases where a comment would be added without a space beforehand, so if the `strings.IndexRune` call on [line 188](https://github.com/peterbourgon/ff/blob/979ab8ea50a3d6af940f159d81037b01ebe5bac1/parse.go#L188) instead were `string.Index(value, " #")`, that'd solve this issue and I think still cover all legit uses.

**Comment by peterbourgon** [comment]
Hmm. I think I agree.
