### ISSUE TITLE
toml dependency and modules

### ISSUE THREAD

**Issue by crawshaw** [peterbourgon/ff#19]
This is a very nice package that I'm considering using.

I don't want to introduce a toml dependency in my project. This is easily fixed as I will vendor this code and remove the toml-related code when I do. But it leaves me wondering: is there a better way to do this under modules? I thought about sending a PR with the toml code moved to a fftoml package, but that still leaves the module dependency. Is there some other way to do this?

**Comment by flowchartsman** [comment]
Can't you just move all toml code to a subdirectory and initialize that as its own module?

```
$ git clone --depth=1 --branch=master git@github.com:peterbourgon/ff
$ rm -rf .git go.mod go.sum
$ mkdir toml
$ mv toml*.go toml
$ cd toml
$ # EDIT EDIT
$ head -n1 toml.go
package toml // import "github.com/peterbourgon/ff/toml"
$ go mod init
go: creating new go.mod: module github.com/peterbourgon/ff/toml
$ go build ./...
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/BurntSushi/toml v0.3.1
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/BurntSushi/toml v0.3.1
$ cat go.mod
module github.com/peterbourgon/ff/toml

require (
	github.com/BurntSushi/toml v0.3.1
	github.com/pkg/errors v0.8.1
)
$ cat go.sum
github.com/BurntSushi/toml v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
github.com/BurntSushi/toml v0.3.1/go.mod h1:xHWCNGjB5oqiDr8zfno3MHue2Ht5sIBksp03qcyfWMU=
github.com/pkg/errors v0.8.1 h1:iURUrRGxPUNPdy5/HRSm+Yj6okJ6UtLINN0Q9M4+h3I=
github.com/pkg/errors v0.8.1/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
$ cd ..
$ vi parse.go
$ # EDIT EDIT (not considering testing changes)
$ head -n1 parse.go
package ff // import "github.com/peterbourgon/ff"
$ go mod init
go: creating new go.mod: module github.com/peterbourgon/ff
$ go build ./...
$ cat go.mod
module github.com/peterbourgon/ff

require github.com/pkg/errors v0.8.1
$ cat go.sum
github.com/pkg/errors v0.8.1 h1:iURUrRGxPUNPdy5/HRSm+Yj6okJ6UtLINN0Q9M4+h3I=
github.com/pkg/errors v0.8.1/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
```

**Comment by crawshaw** [comment]
That's easy! WDYT @peterbourgon, of an fftoml package?

**Comment by peterbourgon** [comment]
SGTM. I hinted at this in [the YAML issue](#9) too. And +1 to `fftoml` instead of just `toml`.

**Comment by flowchartsman** [comment]
`fftoml` is better, sure. I just got caught up in expediency.  Also, depending on how separate you want to keep them, you could consider removing references to `Option`, `WithConfigFile`, `WithConfigFileParser`, and `Parse` from `toml_test.go` and just test its set functionality in isolation.

**Comment by FiloSottile** [comment]
Nested modules are a Pandora's box of complexity. If you don't import `fftoml`, the module-level dependency is irrelevant: it will not be downloaded by `go get`, it will not be vendored by `go mod vendor` and it will not show up anywhere in your `go.mod`.

**Comment by crawshaw** [comment]
@FiloSottile is there something more to the complexity of a nested module than that fftoml ends up depending on ff? Put another way: if fftoml were its own repository, would things be simpler?

(Nested modules do feel complex to me, but only because any dependency system feels complex to me.)

It is a good point that the list in go.mod is not necessarily your list of dependencies. There is something deeply satisfying about a 1-line go.mod file though...

**Comment by peterbourgon** [comment]
To be clear, @FiloSottile, the counterproposal is package ff and package fftoml as separate, but a single go.mod in the root of the repo?

**Comment by flowchartsman** [comment]
Okay, but if you move the TOML stuff into `ff/fftoml`, but forget to `go build ./...` in the root, nothing about `BurntSushi/toml` will appear in *go.mod* or *go.sum*.  You'd assume that you'd still want to track _which_ version of `BurntSushi/toml` to use if including `fftoml`.

So then `go build ./...` is a best practice to make sure nothing's missed?  I'm trying to remember if I read that anywhere in my attempts to familiarize myself with go modules.  I'm kind of in @crawshaw 's late adopter boat myself with modules for this reason.

**Comment by peterbourgon** [comment]
Given go.mod/go.sum applies transitively to subdirectories absent another go.mod/go.sum along the route, `./...` or equivalent feels like a natural practice to me.

**Comment by flowchartsman** [comment]
Well, I mean it's certainly a good idea to `go test ./...` before checking in, so long as you remember to always check in your *go.mod* and *go.sum* after you do so.  It's a little awkward, but then so are dependency management systems.

**Comment by ChrisHines** [comment]
`go mod tidy`

**Comment by ChrisHines** [comment]
See also: https://github.com/golang/go/wiki/Modules#how-to-prepare-for-a-release

**Comment by FiloSottile** [comment]
> @FiloSottile is there something more to the complexity of a nested module than that fftoml ends up depending on ff? Put another way: if fftoml were its own repository, would things be simpler?

Yeah, nested modules carve a hole in the filesystem of the parent module, and the two modules become separate entities while still sharing tag numbers, and you risk having the same package be defined by two modules, and more stuff I don't really understand. Consider that each golang.org/x repo is going to be a single module.

> It is a good point that the list in go.mod is not necessarily your list of dependencies. There is something deeply satisfying about a 1-line go.mod file though...

Your go.mod can still be one line! Transitive dependencies are not listed unless the direct dependency doesn't have a go.mod at all.

> To be clear, @FiloSottile, the counterproposal is package ff and package fftoml as separate, but a single go.mod in the root of the repo?

Yup.

About go.mod getting updated, I expect this to become a non-issue as tooling and editors adapt to modules, as hopefully you'll build/test/autocomplete the code at least once after adding a dependency.

**Comment by peterbourgon** [comment]
> Yup.

Great. I've proposed a patch in the PR #22 that should put things in the suggested state.
