### ISSUE TITLE
Option to skip environmental variables

### ISSUE THREAD

**Issue by directionless** [peterbourgon/ff#23]
I find that sometimes I want to skip environmental variable parsing. (for example, on windows, where that's a bit odd)

From the code, it looks like using `WithEnvVarPrefix("")` should behave this way, but it's not documented. (or simply omitting that option)

I think this is a request for a slight bit of doc tweaking. If my understanding is correct, I'm happy to PR it

**Comment by peterbourgon** [comment]
You have to opt-in to parsing from any source other than commandline flags. So, by default, you don't get any parsing from env vars. I would happily take a PR with doc updates to make this explicit. I guess it should be mentioned in relevant doc comments as well as the README.
