### ISSUE TITLE
Is it possible to Parse into a struct instead of separate variables?

### ISSUE THREAD

**Issue by e-nikolov** [peterbourgon/ff#24]
I would like to be able to "Unmarshal" all flags and configs coming from a config file into a struct rather than have separate variables for each flag. As far as I can tell there is no support for it right now, but would it be possible to achieve by implementing a new ConfigFileParser? And if it is possible, would a PR be accepted for a subpackage that contains that parser similarly to the fftoml parser?

**Comment by peterbourgon** [comment]
This is easily accomplished today.

```go
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/peterbourgon/ff"
)

func main() {
	var config struct {
		s string
		i int
	}

	fs := flag.NewFlagSet("my-program", flag.ExitOnError)
	fs.StringVar(&config.s, "s", "abc", "a string")
	fs.IntVar(&config.i, "i", 123, "an integer")
	ff.Parse(fs, os.Args[1:])

	fmt.Printf("%#v\n", config)
}
```

```
$ go run main.go -s hello -i 42
struct { s string; i int }{s:"hello", i:42}
```
