### ISSUE TITLE
ffcli: add an example

### ISSUE THREAD

**Issue by josharian** [peterbourgon/ff#42]
It'd be nice to have a small sample `func main` in the ffcli docs as a starting place. For example, it took me a few minutes to realize that I needed to pass `os.Args[1:]` to `Command.Run`, not `os.Args`.

**Comment by peterbourgon** [comment]
Absolutely. I'm working on it in #38. I'll close when that's done.

**Comment by josharian** [comment]
Oh, I see that now. I skimmed #38 but missed that. I'll close this now. Thanks!
