### ISSUE TITLE
Should `Parse` fail on missing config file?

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [peterbourgon/ff#46]
Currently if `ff` is configured for using config file:
```
ff.Parse(fs, os.Args[1:], 
ff.WithConfigFile(appName+".conf"),
ff.WithConfigFileParser(ff.PlainParser))
```
And if that config file is missing, `Parse` fails. However it might be perfectly valid state, using defaults for the flags, and failing only if there is no default value for given flag.

**Comment by peterbourgon** [comment]
I think it's totally reasonable to have an option to control this behavior, e.g. func WithAllowMissingConfigFile(allow bool) Option — default false to preserve current behavior.

**Comment by Dragomir-Ivanov** [comment]
Thanks @peterbourgon . Will make a PR in next couple of days. Cheers!

**Comment by johnrichardrinehart** [comment]
@Dragomir-Ivanov it seems that [you've implemented](https://github.com/Dragomir-Ivanov/ff/commit/c834a8c274c60b0cb61c16b52ceafb5731005e52) said functionality. Are you still willing and able to submit a PR?

**Comment by peterbourgon** [comment]
Oops, this is done, the issue should have been closed.

**Comment by johnrichardrinehart** [comment]
[I see](https://github.com/peterbourgon/ff/pull/47). My mistake. Carry on, @Dragomir-Ivanov!

**Comment by Dragomir-Ivanov** [comment]
No worries @johnrichardrinehart. Cheers!
