### ISSUE TITLE
ffcli: recommended way to share non-global flags between some commands?

### ISSUE THREAD

**Issue by moul** [peterbourgon/ff#49]
Hi, thank you for this repo :+1: 

I often have CLI apps that share some flags for specific commands and often feel that my code is not good enough when duplicating similar flags.

Duplicating code is not so much a problem, but having to maintain multiple copies in sync scares me :)

I just created a demo repo here: https://github.com/moul/test-ff-cli/blob/master/main.go

In this repo I have:
* global variables (`verbose`) -> no problem
* per-command unique variables (`bar`, `baz`) -> no problem
* per-command shared variables (`foo`) -> problem

---

Ideas I had that I don't like so much:

1. nesting my subcommands in a shared parent with the common FlagSet -> I prefer to have as few deepness levels as possible in my CLI; it won't address more complex examples where the shared variables are not the same everywhere
2. create flag constructor functions that return the same flag multiple time to avoid maintaining my copies; this solution works but loses a little bit the beautify of `ffcli` which is very easy to read

---

Ideas I had that I would prefer:

* change `Command.FlagSet` to `Command.FlagSets` and allow having multiple flag sets
* add a new helper in ffcli that would help manage this kind of needs
* just recommend a way to address this without modifying `ffcli`

Thank you for reading

**Comment by peterbourgon** [comment]
Does this do what you want?

```go
var sharedFoo bool
aaaFlags.BoolVar(&sharedFoo, "foo", false, "the foo parameter")
bbbFlags.BoolVar(&sharedFoo, "foo", false, "the foo parameter")
```

**Comment by moul** [comment]
Yup :)

It solves the variable name consistency across the whole main

I'll just add constants for shared flag descriptions and default values and I'm done

Thx

**Comment by thomasf** [comment]
This still doesn't feel really solved. Having one config file for the whole program and only having to load it once should be much smoother than it is now.

**Comment by jschaf** [comment]
I found a pretty clean solution, use a function to copy flags into flag sets that you use in each sub-command.

```go
var globalFlags = func() *flag.FlagSet {
	fset := flag.NewFlagSet("global", flag.ExitOnError)
	logflag.DefineFlags(fset)
	return fset
}()

// withGlobalFlags adds the global flags to the FlagSet.
func withGlobalFlags(fset *flag.FlagSet) *flag.FlagSet {
	globalFlags.VisitAll(func(f *flag.Flag) {
		fset.Var(f.Value, f.Name, f.Usage)
	})
	return fset
}
```

Then wrap the subcommand flag sets using `withGlobalFlags`. Modify as needed for different scopings.


```go
func newNestedCmd() *ffcli.Command {
	deployFlagSet := flag.NewFlagSet("some-nested-cmd", flag.ExitOnError)
	return &ffcli.Command{
		FlagSet: withGlobalFlags(deployFlagSet),
	}
}
```

The solution is easily generalizable by creating new `withCustomFlags`. The benefit of this approach is that the only boilerplate in sub-commands is the `withGlobalFlags` function call. I'm pretty happy with this tradeoff. It feels like the right balance between expressiveness and verbosity.
