### ISSUE TITLE
Proposal: fflag package

### ISSUE THREAD

**Issue by GeorgeMac** [peterbourgon/ff#54]
I got bitten the other day by not knowing about `ff.WithEnvVarIgnoreCommas(...)`.

I decided to use a `flag.StringVar(...)` with `ff` and I had set up an env var prefix `ff.WithEnvVarPrefix("INCIDENT")` on a project at work.

This string var was to contain comma-separated list of values. I actually did this with two different config variables. Then I was using `strings.Split(var, ",")` myself on the result.
Later on I observed for both of these config values only the last item in the comma-separated list was being retrieved 🤔. This is where some code and doc spelunking turned up:
https://github.com/peterbourgon/ff/blob/085a4d0bbb8303670222fe06dd00683d8b0b5a75/parse.go#L85-L96

To get things working I switched to using `ff.WithEnvVarIgnoreCommas(true)` for now.

I have a couple proposals after this experience:

1. Some improvements to the docs to make this default behaviour a little clearer. Maybe something in `README.md` to accompany the godoc? If you don't read the docs for `ff.WithEnvVarIgnoreCommas(...)` this behaviour is easy to miss.
2. Now that I know that I can lean on `ff` to do the split and call `flag.Set()` with each value. I could solve the problem with a custom `flag.Value` implementation coupled with `flag.FlagSet.Var(...)`. Perhaps `ff` could provide some custom flag definitions in a `fflag` package?

For example a `fflag.StringsVar(...)` which could be used like:

```go
var strings []string
fs := flag.NewFlagSet()
fflag.StringsVar(fs, strings, "some-strings", []string{"a", "b"}, "some comma separated strings")
```

Unsure right now of another useful ones 😂 But I can confirm this would be useful (for me at least).

**Comment by peterbourgon** [comment]
> Some improvements to the docs to make this default behaviour a little clearer. Maybe something in README.md to accompany the godoc?

I'll happily make this change.

> ... fflag package ... 

I often create an e.g. StringSet type that implements flag.Value by having each Set append the value to a collection of values, rather than overwriting the singular value.

```go
// OrderedStringSet is a slice of strings that implements flag.Value.
// The same flag can be passed multiple times to append to the slice.
// Duplicates are rejected.
type OrderedStringSet []string

// Set implements flag.Value by appending to the slice.
// Duplicate values are rejected with an error.
func (ss *OrderedStringSet) Set(value string) error {
	for _, existing := range *ss {
		if value == existing {
			return errors.New("duplicate")
		}
	}
	(*ss) = append(*ss, value)
	return nil
}

// String implements flag.Value.
func (ss *OrderedStringSet) String() string {
	return strings.Join(*ss, ", ")
}
```

I'm not sure this makes sense to include in package ff itself, or a subpackage. Maybe it does. What other types would you want in addition to that one?

**Comment by GeorgeMac** [comment]
Yeah, perhaps it would be overkill :D I can't think of any other types off the top of my head haha.
I could probably fabricate some examples, but that is not really a justification for adding a new package 😂

Thanks for addressing the docs!

**Comment by GeorgeMac** [comment]
Not sure if this is premature to close, but I see the new comment cheers @peterbourgon ! I will close for now, I think the `fflag` package is premature without enough good ideas :)
