### ISSUE TITLE
ffcli: Two-phase apps complicate noop handling

### ISSUE THREAD

**Issue by codahale** [peterbourgon/ff#57]
Noop commands (i.e., have subcommands but no exec) can be handled in a one-phase app pretty easily by having the command return `flag.ErrHelp`, so that users who accidentally call it get usage help instead of nothing. That’s good.

But it gets awkward in a two-phase app, especially when the initialization involves logging output. A user would get usage help on stderr and logging output on stdout interleaved. Unless I’m missing something, this is not currently possible. It would be nice to be able to specify that `Parse` mimic the `flag.ExitOnError` functionality on noops, or at least a `Noop() bool` method so the initialization phase can be avoided.

I’m happy to put together a PR for this, but I wanted to raise the issue first in case I’m missing something and to get your input on preferred solutions.

**Comment by peterbourgon** [comment]
Thanks for the issue.

If you call Parse and then Run, and the Command chosen by Parse has an Exec that returns flag.ErrHelp — this is my understanding of what you mean by "no-op command" — then it should give the behavior you're asking for, right?

I mean, I guess not, since you filed the issue :) So what's the difference between what I described, and what you're looking for?

**Comment by peterbourgon** [comment]
Ah, OK —

> Noop commands (i.e., have subcommands but no exec)

```go
func (c *Command) Run(ctx context.Context) (err error) {
	var (
		unparsed = c.selected == nil
		terminal = c.selected == c && c.Exec != nil
		noop     = c.selected == c && c.Exec == nil
	)

	// ...

	switch {
	case unparsed:
		return ErrUnparsed
	case terminal:
		return c.Exec(ctx, c.args)
	case noop:
		return nil
```

I forgot about this "noop command" — sorry for that confusion. But I think everything else I wrote still holds. 

Are you saying you want the Parse phase to return a non-nil error if it chooses a Command whose Exec returns flag.ErrHelp? Which might transitively mean you want a different way to declare Commands that have no actual behavior but should emit the usage text, such that they're detectable by the Parse phase?

**Comment by codahale** [comment]
Yep. It would be nice to be able to indicate that some commands are not invocable, but are rather just collections of subcommands.

For example, `my-app things list` is valid but `my-app things` should just print usage info w/o involving any potential side effects created in between parsing and running.

This might also mean that it’d also be nice to be able to validate flags and args during the parse phase.

**Comment by peterbourgon** [comment]
If Parse returned a sentinel error for `case noop` instead of `nil`, would that solve your problem?

**Comment by codahale** [comment]
I think it would, yeah.

**Comment by codahale** [comment]
Just thinking this out — a sentinel error would work, but being able to access the selected command would allow for sub-command specific usage info. That’s not necessary, of course, but it might be nice.

**Comment by peterbourgon** [comment]
👍 I'll make a PR with that, or something like it, in the next day or so.

**Comment by codahale** [comment]
That’d be perfect.

**Comment by peterbourgon** [comment]
Will #58 do it for you?

**Comment by codahale** [comment]
Looks great!

**Comment by peterbourgon** [comment]
Fixed in v3.
