### ISSUE TITLE
WithIgnoreUndefined(true) does not ignore undefined flags

### ISSUE THREAD

**Issue by cbandy** [peterbourgon/ff#59]
`ff.Parse(..., ff.WithIgnoreUndefined(true))` stops parsing arguments at the first undefined flag. See https://github.com/golang/go/issues/15352 and https://play.golang.org/p/qpJ1FeEjZGS:
```go
package main

import (
	"flag"
	"fmt"

	"github.com/peterbourgon/ff/v3"
)

func main() {
	var known string

	fs := flag.NewFlagSet("", flag.ContinueOnError)
	fs.StringVar(&known, "known", "default", "usage")
	err := ff.Parse(fs, []string{"-unknown", "-known=set"}, ff.WithIgnoreUndefined(true))

	fmt.Printf("known %q, err: %v\n", known, err)
}
```
```
flag provided but not defined: -unknown
Usage:
  -known string
    	usage (default "default")
known "default", err: error parsing commandline args: flag provided but not defined: -unknown
```

---

I was hopeful that `ff.Parse()` would behave differently from `flags.Parse()` in this case, but I see that it delegates:

https://github.com/peterbourgon/ff/blob/b4729673e63b95b7844770f030138337499e9927/parse.go#L21-L24

I recognize the relationship this package has to `flags`, so rather than some functionality change, perhaps this limitation should be documented.

**Comment by peterbourgon** [comment]
Oops, might be a regression, might be a docs issue. Will investigate...

**Comment by peterbourgon** [comment]
Yep, it's a docs issue: that option only affects undefined flags in config files. Thanks for the note, I'll update the documentation and mention a suggested workaround.

**Comment by peterbourgon** [comment]
Updated the docs, but, unfortunately, no non-awful workaround is possible, due to the design of stdlib package flags. Sorry for the confusion, and sorry I don't have better news.

**Comment by cbandy** [comment]
Thank you for the swift response!
