### ISSUE TITLE
Handle fallbacks in options... order

### ISSUE THREAD

**Issue by carlmjohnson** [peterbourgon/ff#7]
On Reddit, the thing [people seemed to want](https://www.reddit.com/r/golang/comments/a3pitv/flagsfirst_package_for_configuration/eb8sx3z/) was the ability to specify the priority of env vars vs. config files. What if that was controlled by the order of the items in the options... vararg? Too clever?

**Comment by peterbourgon** [comment]
Yeah, that's too clever. If this will be configurable, it should be an option: WithEnvVarPriority, WithConfigPriority. I think I also got it wrong right now, the default priority order should be: flags, env vars, config file.
