### ISSUE TITLE
Feature request: ability to provide a default config file path

### ISSUE THREAD

**Issue by nyonson** [peterbourgon/ff#80]
I would like to provided a default configuration file based on XDG (e.g. `~/.config/APP.config`) which could then be overwritten by `WithConfigFileFlag` if a user prefers a different location. I was surprised to find that with the existing settings `WithConfigFile` overwrites `WithConfigFileFlag`, is there a use case for this that I am missing?

**Comment by peterbourgon** [comment]
`WithConfigFile` is provided only so there is a way to set a config file without going through a flag set, but that is a very rare circumstance. If you want to provide an e.g. `-config-file` flag with a default path, just define it as a flag and use that path as the flag default.

```go
configPath, err := os.UserConfigDir()
if err != nil {
    log.Fatal(err)
}

defaultConfigFile := filepath.Join(configPath, "myctl", "myctl.conf")

fs := flag.NewFlagSet("myctl", flag.ContinueOnError)
var (
    foo = fs.String("foo", "hello world", "foo flag")
    _   = fs.String("config-file", defaultConfigFile, "config file")
)
if err := ff.Parse(fs, os.Args[1:], ff.WithConfigFileFlag("config-file")); err != nil {
    log.Fatal(err)
}
```

**Comment by nyonson** [comment]
Ah, I totally misinterpreted how `WithConfigFileFlag` worked, thanks for the example. I went with your solution.
