### ISSUE TITLE
Question Re: Yaml Parser

### ISSUE THREAD

**Issue by aramcodz** [peterbourgon/ff#81]
On our team is using the [ff Yaml parser](https://github.com/peterbourgon/ff/blob/main/ffyaml/ffyaml.go). 

We came across a possible use case where we may have the config.yaml file that has several string/scalar fields that contain an empty str value, as in:
  
```
  propertyOne: "someVal"
  propertyTwo: 
  log-level: "Debug" 
```

where `propertyTwo` is  an empty string field.

When the yaml parser tries to read in one of these yaml files, it returns this error: 
  
`   error parsing YAML config: couldn't convert %!q(<nil>) (type <nil>) to string`
   
I noticed that the test case "no value" in https://github.com/peterbourgon/ff/blob/main/ffyaml/ffyaml_test.go actually expects an empty string value for a yaml field to return this error.

But, the YAML 1.2 Spec does say it allows empty scalar values that should resolve to the "null" tag (tag:yaml.org,2002:null). See https://yaml.org/spec/1.2/spec.html#id2805071. 

Is there a specific reason that ff Yaml Parser returns this (not very helpful/descriptive) error for an empty string value in the yaml file? We assumed that empty field values would be supported.

**Comment by peterbourgon** [comment]
If it's not to spec I'll happily take a fix, but with the caveat that I'm no YAML guru, I'm not sure this can actually work. You call this an empty string value, but how do you know it's not a boolean? Or an array?

**Comment by peterbourgon** [comment]
At a minimum the error message should be improved by annotating (prefixing) it with the key that triggered the problem.

**Comment by aramcodz** [comment]
> If it's not to spec I'll happily take a fix, but with the caveat that I'm no YAML guru, I'm not sure this can actually work. You call this an empty string value, but how do you know it's not a boolean? Or an array?


From the Yaml 1.2 spec ([section 7.2 - Empty Nodes](https://yaml.org/spec/1.2/spec.html#id2786563)):

> YAML allows the node content to be omitted in many cases. Nodes with empty content are interpreted as if they were plain scalars with an empty value. Such nodes are commonly resolved to a “null” value.

I believe that for any scalar field where they key is present but has empty value, the YAML Spec itself, says that it interprets that value as a `null` "type".  See https://stackoverflow.com/a/64462925/5414775. 

So, perhaps I should be more specific in YAML terms. 

In my example here:

```
  propertyOne: "someVal"
  propertyTwo: 
  log-level: "Debug" 
```

`propertyTwo`'s "key" should be interpreted as a string by the parser, while the value for this node is of type null (tag:yaml.org,2002:null) with the value "null".  For reference, [this SO response](https://stackoverflow.com/a/836370/5414775) to a similar question shows how the YAML for the field "key" with an empty value should be parsed in (the slightly older, 1.1 version of) Yaml. 

Hence, the intended datatype of the empty node really doesn't matter.  For the purposes of writing a compliant YAML parser in a strongly-typed language, I think that one can just always assume that an empty node/value type is string.

**Comment by peterbourgon** [comment]
OK, if you're convinced it can work, happy to see a PR 👍

**Comment by aramcodz** [comment]
PR for this proposed change -> https://github.com/peterbourgon/ff/pull/82
