### ISSUE TITLE
Yaml config parser 

### ISSUE THREAD

**Issue by karthikmuralidharan** [peterbourgon/ff#9]
At our company we heavily use yaml for configurations between env. 

I would like to try out using this package on one of our new services. Would you be open to accepting a yaml config parser implementation ?

**Comment by peterbourgon** [comment]
Sure.

**Comment by carlmjohnson** [comment]
I would prefer this not go into the ff package, because it will add a dependency on whatever YAML package you choose. What about publishing a separate package for YAML parsing?

**Comment by peterbourgon** [comment]
Agree, subpackage ffyaml.

**Comment by karthikmuralidharan** [comment]
Sounds good.

**Comment by peterbourgon** [comment]
We've got package ffyaml now via #31.
