### ISSUE TITLE
flags/env vars

### ISSUE THREAD

**Issue by jimenezna06** [peterbourgon/ff#91]
I noticed that ffcli and ff doesn’t seem to load config from env vars. Is there a way to make sure it defaults to env vars? instead of having the flag override the env var if an env var exists. 
I am using the function:
`ff.Parse(fs, os.Args[1:], ff.WithEnvVarNoPrefix())`

**Comment by peterbourgon** [comment]
To be clear, you're saying that

```
env FOO=123 myprogram -foo=456
```

should set foo to 123, not 456?

**Comment by jimenezna06** [comment]
if you set a flag the exec uses the flag
if no flag is set it used env var
if nothing is set it doesn’t work
in other words a flag overrides the env var if an env var exists
unless ff doesn’t allow it but I think it does?

does it allow this?

**Comment by peterbourgon** [comment]
What you described is exactly how it works currently. Is it not the case for you?
