### ISSUE TITLE
feature request: camelCase flag to snake_case env

### ISSUE THREAD

**Issue by lmittmann** [peterbourgon/ff#99]
Great package. It would be nice if a camelCase flag names could be set by an env variable in snake_case.

Example:
```go
fs := flag.NewFlagSet("my-program", flag.ContinueOnError)
rpcURL = fs.String("rpcURL", ...)
```
This works: `$ RPCURL="https://..." my-program`
This does not work (would be nice though):  `$ RPC_URL="https://..." my-program`

**Comment by peterbourgon** [comment]
I'm not aware of a way to reliably tokenize camel case identifiers in this way. If you know of one, please re-open with a link!

**Comment by peterbourgon** [comment]
Ehhh not sure it's OK to assume camel can be interpreted as raw bytes, and not convinced that some of those test cases necessarily tokenize in the way which is asserted. I appreciate the effort! But this is in my judgment too fragile.
